
TOP = ..

SUBDIRS += alarm
#SUBDIRS += bc           uses old (non-existent?) bc code
SUBDIRS += creat
SUBDIRS += env-perf
SUBDIRS += ether
SUBDIRS += exec
SUBDIRS += externalalloc
SUBDIRS += filedump
SUBDIRS += float
SUBDIRS += flock
SUBDIRS += ipctest
#SUBDIRS += lb            kernel support removed
SUBDIRS += libc/gethostbyaddr
SUBDIRS += memory
#SUBDIRS += microbm       uses ash code
SUBDIRS += micropart
SUBDIRS += mount
SUBDIRS += netbsd
SUBDIRS += nullkerncall
SUBDIRS += ppstates
SUBDIRS += ptytest
SUBDIRS += scsicmd
SUBDIRS += stdio
#SUBDIRS += sumcompare	# needs to be updated to new sys_disk_request
#SUBDIRS += tcp-client    uses old (non-existent?) tcp code
#SUBDIRS += tcp-handoff   uses old (non-existent?) tcp code
#SUBDIRS += tcp-server    uses old (non-existent?) tcp code
SUBDIRS += tsleep
#SUBDIRS += udp           uses old (non-existent?) udp code
SUBDIRS += udpconnect
SUBDIRS += vm-perf
SUBDIRS += wafer          # uses setmagic (might not work with linux)
SUBDIRS += wk-test
SUBDIRS += xio-demo

include $(TOP)/GNUmakefile.global
