
TOP = ../..
SUBDIRS = simple-test \
          tst-printf \
          test_rdwr \
          test-fseek \
          bug2 \
          bug3 \
          bug4 \
          bug6 \
          temptest \
          tst-fileno \
          tstscanf \
          bug5 \
          test-popen \
          xbug   # need popen, pclose \
          #tstgetln  # no getline() \
          #bug1  # no open_memstream() \

include $(TOP)/GNUmakefile.global
