
TOP = ../..
PROG = test_ffs.b
SRCFILES = test_ffs.c
EXTRATRG = test_ffs.b.s
EXTRAOBJ = ../../lib/libc/obj/libc.a ../../lib/ffs/obj/libffs.a
LIBS = ../../lib/libc/obj/libc.a

include $(TOP)/GNUmakefile.global
