
TOP = ../..
OBJDIR = obj
STATIC=1
EXTRAINC = -I.. -I../../libc -I.
LIB = libtelnet.a
DEFS = -Dlint -DHAS_CGETENT 
EXTRACLN = 
UNINITOK =
UNUSEDOK = genget.c


SRCFILES= auth.c encrypt.c genget.c getent.c misc.c
export DOINSTALL=yes

include $(TOP)/GNUmakefile.global
