
VPATH += $(VOS)/voslibc/termios
SRCFILES+= cfgetispeed.c cfgetospeed.c cfmakeraw.c cfsetispeed.c \
	cfsetospeed.c cfsetspeed.c tcdrain.c tcflow.c tcflush.c \
	tcgetattr.c tcgetpgrp.c tcsendbreak.c tcsetattr.c tcsetpgrp.c
