
VPATH += $(VOS)/voslibc/string
SRCFILES+= strxfrm.c swab.S __strsignal.c strpbrk.c strrchr.S strsep.c \
	strsignal.c strspn.c strstr.c __strerror.c strerror.c strlcat.c \
	strlcpy.c strmode.c strncat.c bm.c index.S memccpy.c memchr.S \
	rindex.S strcasecmp.c strchr.S strcoll.c strcspn.c strdup.c \
	strcmp.S memmove.S memset.S strcat.S strcpy.S strlen.S strncmp.S \
	strncpy.c strtok.c bcmp.S bcopy.S bzero.S ffs.S memcmp.S memcpy.S 
