
TOP = ../..
OBJDIR = obj
STATIC=1
EXTRAINC = -I.. -I../../libc -I.
LIB = libtermcap.a
DEFS =  -DCM_N -DCM_GT -DCM_B -DCM_D
UNINITOK =
UNUSEDOK = termcap.c tgoto.c tputs.c

export DOINSTALL=yes

SRCFILES=	termcap.c tgoto.c tputs.c
include $(TOP)/GNUmakefile.global
