
VPATH += $(VOS)/voslibc/compat-43
SRCFILES += __setreuid.c __setregid.c creat.c getdtablesize.c gethostid.c \
	getwd.c killpg.c sethostid.c setpgrp.c setregid.c setreuid.c \
	setrgid.c setruid.c sigcompat.c

