
TOP = ../../..
EXTRAINC = -I$(CURDIR)/../.. -I$(TOP)/lib/libexos
STATIC = 1
LIB = ../libalfssep.a

VPATH = ..
SRCFILES = alfs_alloc.c alfs_dir.c alfs_path.c alfs_dinode.c \
           alfs_syscalls.c alfs_buffer.c buffer_tab.c \
           alfs_defaultcache.c alfs_inode.c name_cache.c \
           protection.c alfs_rdwr.c

include $(TOP)/GNUmakefile.global
