TOP = ../../../..

all::
	@echo -n

install::
	$(INSTALL) -c -m 444 ascii $(ROOT)/usr/share/misc
	$(INSTALL) -c -m 444 gprof.callg $(ROOT)/usr/share/misc
	$(INSTALL) -c -m 444 gprof.flat $(ROOT)/usr/share/misc
	$(INSTALL) -c -m 444 keycap.pcvt $(ROOT)/usr/share/misc
	$(INSTALL) -c -m 444 more.help $(ROOT)/usr/share/misc
	$(INSTALL) -c -m 444 termcap $(ROOT)/usr/share/misc
	$(INSTALL) -c -m 444 termcap.db $(ROOT)/usr/share/misc
	$(INSTALL) -c -m 444 terminfo.db $(ROOT)/usr/share/misc

include $(TOP)/GNUmakefile.global
