# program execs itself ITER times.
TOP = ../..
PROG = exec-perf
SRCFILES = exec-perf.c default_modules.c

DOINSTALL=yes
INSTALLPREFIX=bin
EXTRAINC = -I../../lib/libc
include $(TOP)/GNUmakefile.global
