
TOP = ../..
OBJDIR = obj
STATIC=1
EXTRAINC = -I.. -I../../libc -I.
LIB = libz.a
DEFS =  
EXTRACLN = 
UNINITOK =
UNUSEDOK =

export DOINSTALL=yes


SRCFILES= adler32.c compress.c crc32.c deflate.c gzio.c infblock.c \
        infcodes.c inffast.c inflate.c inftrees.c infutil.c trees.c \
        uncompr.c zutil.c

include $(TOP)/GNUmakefile.global
