TOP = ../../../..

all::
	@echo -n

install::
	$(INSTALL) -c -m 444 bsd.README $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.dep.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.doc.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.lib.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.lkm.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.man.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.nls.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.obj.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.own.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.port.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.port.subdir.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.prog.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.subdir.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 bsd.sys.mk $(ROOT)/usr/share/mk
	$(INSTALL) -c -m 444 sys.mk $(ROOT)/usr/share/mk

include $(TOP)/GNUmakefile.global
