#
# Used to generate stub files from a shared library. Apps then link
# against this stub file so that they know where lib symbols will
# be in their address space at run time.

TOP = ../..
AUXPROGS = mkspec
EXTRATRG = $(AUXPROGS)
include $(TOP)/GNUmakefile.global
