
TOP = ..

SUBDIRS += bintoc
SUBDIRS += mkspec
SUBDIRS += rconsole
SUBDIRS += senddocs
SUBDIRS += vm-layout
#SUBDIRS += pad		# used with ashes - doesn't work on linux
#SUBDIRS += rawdisk	# out of date disk manipulation programs
SUBDIRS += setmagic	# sets the magic number of an executable - used
			#  by libwafer programs, but doesn't work on linux
#SUBDIRS += symset	# doesn't work on linux
#SUBDIRS += unix-tcp	# old - probably should be removed
#SUBDIRS += unix-udp	# old - probably should be removed

include $(TOP)/GNUmakefile.global
