#
# rconsole is used to conned to the hsh on exomachines, so you can run
# programs, etc.
#
# use rconsole -help 
# for more information
#

TOP = ../..
AUXPROGS = rconsole
EXTRATRG = $(AUXPROGS)
include $(TOP)/GNUmakefile.global
