
TOP = ../..
OBJDIR = obj
EXTRAINC = -I$(CURDIR) -I$(TOP)/lib/libc
LIB = libffs.a

SRCFILES = disk.c ffs.c ffs_file.c ffs_dir.c ffs_internal.c \
	ffs_balloc.c ffs_bmap.c ffs_alloc.c ffs_subr.c ffs_tables.c

include $(TOP)/GNUmakefile.global
