TOP = ..
export ROOT = $(EXODEST)
SUBDIRS = directories \
	etc \
	usr/share/mk \
	usr/share/misc \
	usr/lib

PAXINSTALL = home
#PAXINSTALLPREFIX = home

DOINSTALL=yes

include $(TOP)/GNUmakefile.global
